"use client";

import { useState } from "react";
import { Header } from "@/components/Header";
import { Dropzone } from "@/components/Dropzone";
import { FileList } from "@/components/FileList";
import { FormatGrid } from "@/components/FormatGrid";
import { FaqSection } from "@/components/FaqSection";
import { Footer } from "@/components/Footer";
import { SettingsModal } from "@/components/SettingsModal";
import {
  SITE_CONFIG,
  DEMO_PRESET_FILES,
  type DecryptedFileItem,
} from "@/data/music-data";

export default function Home() {
  const [files, setFiles] = useState<DecryptedFileItem[]>([]);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);

  // Handle files added by user
  function handleFilesAdded(newFiles: File[]) {
    const formattedItems: DecryptedFileItem[] = newFiles.map((file, idx) => {
      const ext = file.name.split(".").pop()?.toUpperCase() || "BIN";
      const targetFormat: "MP3" | "FLAC" =
        ext.includes("FLAC") || ext === "NCM" ? "FLAC" : "MP3";

      // Try parsing Artist - Title from filename
      const baseName = file.name.replace(/\.[^/.]+$/, "");
      const parts = baseName.split("-").map((s) => s.trim());
      const artist = parts.length > 1 ? parts[0] : "未知歌手";
      const title = parts.length > 1 ? parts.slice(1).join(" - ") : baseName;

      return {
        id: `${Date.now()}-${idx}-${Math.random().toString(36).substring(2, 6)}`,
        name: file.name,
        sourceFormat: ext,
        targetFormat,
        size: `${(file.size / (1024 * 1024)).toFixed(1)} MB`,
        title,
        artist,
        album: "未知专辑",
        status: "processing",
        progress: 10,
      };
    });

    setFiles((prev) => [...formattedItems, ...prev]);

    // Simulate multi-threaded fast worker decryption progress
    formattedItems.forEach((item) => {
      let currentProgress = 20;
      const interval = setInterval(() => {
        currentProgress += Math.floor(Math.random() * 30) + 15;
        if (currentProgress >= 100) {
          clearInterval(interval);
          setFiles((prev) =>
            prev.map((f) =>
              f.id === item.id
                ? { ...f, status: "completed", progress: 100 }
                : f
            )
          );
        } else {
          setFiles((prev) =>
            prev.map((f) =>
              f.id === item.id ? { ...f, progress: currentProgress } : f
            )
          );
        }
      }, 150);
    });
  }

  // Load demo preset files
  function handleLoadDemo() {
    setFiles(DEMO_PRESET_FILES);
  }

  // Clear all files
  function handleClearAll() {
    setFiles([]);
  }

  // Remove single file
  function handleRemoveFile(id: string) {
    setFiles((prev) => prev.filter((f) => f.id !== id));
  }

  // Trigger download for single file
  function handleDownload(file: DecryptedFileItem) {
    const filename = `${file.artist} - ${file.title}.${file.targetFormat.toLowerCase()}`;
    const blob = new Blob(
      [
        `Simulated decrypted audio file content for: ${filename}\nOriginal encrypted source: ${file.name}\nGenerated by Unlock Music local converter.`,
      ],
      { type: "audio/mpeg" }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Trigger download for all completed files
  function handleDownloadAll() {
    const completed = files.filter((f) => f.status === "completed");
    completed.forEach((file, index) => {
      setTimeout(() => {
        handleDownload(file);
      }, index * 200);
    });
  }

  const completedCount = files.filter((f) => f.status === "completed").length;

  return (
    <div className="flex min-h-screen flex-col">
      <Header onOpenSettings={() => setIsSettingsOpen(true)} />

      <main className="flex-1">
        {/* Hero & Upload section */}
        <section className="relative overflow-hidden pt-8 pb-4">
          <div className="container mx-auto max-w-5xl px-4 sm:px-6">
            {/* Announcement bar */}
            <div className="mb-6 flex items-center justify-center">
              <div className="inline-flex items-center gap-2 rounded-full border border-sky-500/20 bg-sky-50/80 px-3.5 py-1 text-xs text-sky-700 shadow-xs">
                <span>{SITE_CONFIG.announcement}</span>
              </div>
            </div>

            {/* Core Dropzone Area */}
            <Dropzone
              onFilesAdded={handleFilesAdded}
              onLoadDemo={handleLoadDemo}
              onClearAll={handleClearAll}
              onDownloadAll={handleDownloadAll}
              fileCount={files.length}
              completedCount={completedCount}
            />

            {/* Decrypted Files List */}
            <FileList
              files={files}
              onRemove={handleRemoveFile}
              onDownload={handleDownload}
            />

            {/* Formats Grid */}
            <FormatGrid />

            {/* FAQ Accordion */}
            <FaqSection />
          </div>
        </section>
      </main>

      <Footer />

      {/* Settings Modal */}
      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
      />
    </div>
  );
}
